version: '3.1'

#tener en cuenta:
#docker login container-registry.oracle.com
#Username: aj********@gm***.com
#Password: 
#Login Succeeded

services:

  # Oracle service (label used to access the service container)
  oracle:

    # Docker Hub image (feel free to change the tag "latest" to any other available one)
    image: gvenzl/oracle-xe:latest

    # Provide passwords and other environment variables to container
    environment:
      ORACLE_RANDOM_PASSWORD: true
      APP_USER: steven
      APP_USER_PASSWORD: test123

    # Forward Oracle port
    ports:
      - 1521:1521

    # Provide healthcheck script options for startup
    #options: >-
    #  --health-cmd healthcheck.sh
     # --health-interval 10s
      #--health-timeout 5s
      #--health-retries 10


#services: 
  #oracle-db:
    #image: container-registry.oracle.com/database/enterprise:19.3.0.0 #doctorkirk/oracle-19c 
    #environment:
      #- ORACLE_SID=ORCLCDB
      #- ORACLE_PDB=ORCLPDB1
     # - ORACLE_PWD=Oracle_123
      #- ORACLE_CHARACTERSET=
    #ports:
     # - 1521:1521
     # - 5500:5500
      #- 54321:54321
    #volumes:
    #  - oracle-data:/opt/oracle/oradata
    #  - oracle-backup:/opt/oracle/backup
    #healthcheck:
    #  test: ["CMD", "sqlplus", "-L", "sys/Oracle_123@//localhost:1521/ORCLCDB as sysdba", "@healthcheck.sql"]
    #  interval: 30s
    #  timeout: 10s
    #  retries: 5
    #deploy:
      #resources:
        #limits:
          #cpus: '0.5' # 0.5 = 50%
          #memory: 2048M
        #reservations:
          #cpus: '0.0001'
          #memory: 20M

#volumes:
  #oracle-data:
  #oracle-backup: