

CREATE TABLE AUTHORS (
	ID NUMBER (10,0) GENERATED ALWAYS AS IDENTITY,
	NAME VARCHAR (64),
	CONSTRAINT pk_authors PRIMARY KEY (id)
);




CREATE TABLE BOOKS (
	ID NUMBER (10,0) GENERATED ALWAYS AS IDENTITY,
	NAME VARCHAR (128),
	CONSTRAINT pk_books PRIMARY KEY (id)
);




CREATE TABLE BOOKS_AUTHORS (
	ID_BOOK NUMBER (10,0),
	ID_AUTHOR NUMBER (10,0),
	CONSTRAINT fk_book FOREIGN KEY (ID_BOOK) REFERENCES BOOKS(ID),
	CONSTRAINT fk_author FOREIGN KEY (ID_AUTHOR) REFERENCES AUTHORS(ID),
	CONSTRAINT constraint_unique_row UNIQUE (ID_BOOK, ID_AUTHOR)
);



